### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by alexanderschoenberger** [htl-perg-2018-19-4ahif/angular-todo-example-alexanderschoenberger#1]
https://dreamy-villani-d2556e.netlify.com

**Comment by rstropek** [comment]
Hi @alexanderschoenberger!

Thank you for your solution. Well done 👍. The due date doesn't fully work (edit does not display the originally entered date) but that's just a minor mistake. So two extra points for you.

Greetings,
Rainer Stropek.
